version: '2'
services:
  u235core:
    container_name: u235core
    build: .
    env_file: environment.txt
    entrypoint:
      - /bin/bash
      - -c
    command:
      - NODE_ENV=test /usr/bin/npm run db:migrate && NODE_ENV=test /usr/bin/npm run db:seed && NODE_ENV=development /usr/bin/npm start
    ports:
      - "8000:80"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    depends_on:
      - db
      - db_test
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=u235coredbpassword
      - POSTGRES_USER=u235core
      - POSTGRES_DB=u235core
    ports:
      - "5432:5432"
  db_test:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=u235coredbpassword
      - POSTGRES_USER=u235core
      - POSTGRES_DB=u235core
    ports:
      - "5433:5432"
networks:
  default:
    external:
      name: u235

