module.exports = {
  SYSTEM: 'ALL.*',
  BASIC_OBJECTS_READ: 'BASIC_OBJECTS.READ',

  CLIENTS_CREATE: 'CLIENTS.CREATE',
  CLIENTS_READ: 'CLIENTS.READ',
  CLIENTS_UPDATE: 'CLIENTS.UPDATE',

  COMMENTS_CREATE: 'COMMENTS.CREATE',
  COMMENTS_READ: 'COMMENTS.READ',
  COMMENTS_UPDATE: 'COMMENTS.UPDATE',
  COMMENTS_DELETE: 'COMMENTS.DELETE',

  ROLES_CREATE: 'ROLES.CREATE',
  ROLES_READ: 'ROLES.READ',
  ROLES_UPDATE: 'ROLES.UPDATE',
  ROLES_DELETE: 'ROLES.DELETE',

  USERS_CREATE: 'USERS.CREATE',
  USERS_READ: 'USERS.READ',
  USERS_UPDATE: 'USERS.UPDATE',
}
